- name: remove welcome.conf
  file: >
    path=/etc/httpd/conf.d/welcome.conf
    state=absent

- name: be sure httpd is configured
  template: >
    src=httpd.conf.j2
    dest=/etc/httpd/conf/httpd.conf

- name: create webpagetest directory
  file: >
    path=/var/www/webpagetest/
    state=directory
    owner=apache
    group=apache

- name: be sure httpd is running and enabled
  service: >
    name=httpd
    state=running
    enabled=yes
