- name: be sure yum rpmforge repository is add
  yum: >
    name=http://packages.sw.be/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
    state=present

- name: be sure yum centos repository is add
  template: >
    src=centos.repo.j2
    dest=/etc/yum.repos.d/centos.repo

- name: be sure yum packages are installed
  yum: >
    name={{ item }}
    state=present
  with_items:
    - ffmpeg
    - httpd
    - ImageMagick
    - libcurl
    - php
    - php-fpm
    - php-gd
    - php-pecl-apc
    - unzip
    - zlib
