- name: be sure yum rpmforge repository is add
  command: rpm -Uhv http://packages.sw.be/rpmforge-release/rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm

- name: be sure yum centos repository is add
  template: src=centos.repo.j2 dest=/etc/yum.repos.d/centos.repo

- name: be sure yum packages are installed
  yum: name={{item}} state=installed
  with_items:
    - httpd
    - php
    - php-gd
    - php-pecl-apc
    - zip
    - zlib
    - git
    - gcc